admin_platform_admin_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security::loginAction
        _sylius:
            template: '@PlatformAdmin/Security/login.html.twig'
            permission: true

admin_platform_admin_login_check:
    path: /login-check
    methods: [POST]
    defaults:
        _controller: sylius.controller.security::checkAction

admin_platform_admin_logout:
    path: /logout
    methods: [GET]
